import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";

dotenv.config();

async function main() {
  const feeRecipient = process.env.FEE_RECIPIENT ?? ethers.ZeroAddress;
  const Factory = await ethers.getContractFactory("EscrowFactory");
  const factory = await Factory.deploy(feeRecipient);
  await factory.waitForDeployment();
  const addr = await factory.getAddress();
  console.log("Factory deployed at", addr);

  await exportAbi();
  await exportAddresses(addr);
}

async function exportAbi() {
  const artifactsDir = path.join(__dirname, "../artifacts/contracts");
  const escrowAbi = JSON.parse(fs.readFileSync(path.join(artifactsDir, "Escrow.sol/Escrow.json"), "utf8")).abi;
  const factoryAbi = JSON.parse(fs.readFileSync(path.join(artifactsDir, "EscrowFactory.sol/EscrowFactory.json"), "utf8")).abi;
  const frontend = path.join(__dirname, "../../frontend/src/contracts");
  fs.mkdirSync(frontend, { recursive: true });
  fs.writeFileSync(path.join(frontend, "escrow.abi.json"), JSON.stringify(escrowAbi, null, 2));
  fs.writeFileSync(path.join(frontend, "factory.abi.json"), JSON.stringify(factoryAbi, null, 2));
  console.log("Exported ABI to frontend/src/contracts");
}

async function exportAddresses(factoryAddress: string) {
  const chainId = (await ethers.provider.getNetwork()).chainId;
  const frontend = path.join(__dirname, "../../frontend/src/contracts");
  const addressesPath = path.join(frontend, "addresses.ts");
  const content = `// Auto-generated by deploy script\nexport const FACTORY_ADDRESS_BY_CHAIN: Record<number, \`0x${string}\`> = {\n  ${chainId}: "${factoryAddress}"\n};\nexport const ESCROW_ADDRESS_BY_CHAIN: Record<number, \`0x${string}\`> = {};\n`;
  fs.writeFileSync(addressesPath, content);
  console.log("Exported addresses to", addressesPath);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

